package io.github.windedge.num2words

import kotlin.test.Test
import kotlin.test.assertEquals

/** Golden samples from Python tests/test_es.py (generated). */
class EsTest {
private fun esNum(v: Any, to: String = "cardinal", options: Map<String, Any?> = emptyMap()): Any =
    when (v) {
        // NOTE: on JS every Number is Double. Integral doubles become Long for
        // cardinal/ordinal (Python int parity), but currency keeps Double:
        // float 1.0 means 1 euro with cents, Long 1 means 1 cent.
        is Double -> if (to != "currency" && v % 1.0 == 0.0 && v >= -9.0e18 && v <= 9.0e18) {
            num2words(v.toLong(), lang = "es", to = to, options = options)
        } else {
            num2words(v, lang = "es", to = to, options = options)
        }
        is Float -> if (to != "currency" && v.toDouble() % 1.0 == 0.0) {
            num2words(v.toLong(), lang = "es", to = to, options = options)
        } else {
            num2words(v.toDouble(), lang = "es", to = to, options = options)
        }
        is Long -> num2words(v, lang = "es", to = to, options = options)
        is Int -> num2words(v, lang = "es", to = to, options = options)
        is String -> num2words(v, lang = "es", to = to, options = options)
        else -> num2words((v as Number).toDouble(), lang = "es", to = to, options = options)
    }


    private val CARDINAL = listOf<Pair<Any, String>>(
        1 to "uno",
        2 to "dos",
        3 to "tres",
        5.5 to "cinco punto cinco",
        11 to "once",
        12 to "doce",
        16 to "dieciséis",
        17.42 to "diecisiete punto cuatro dos",
        19 to "diecinueve",
        20 to "veinte",
        21 to "veintiuno",
        26 to "veintiséis",
        27.312 to "veintisiete punto tres uno dos",
        28 to "veintiocho",
        30 to "treinta",
        31 to "treinta y uno",
        40 to "cuarenta",
        44 to "cuarenta y cuatro",
        50 to "cincuenta",
        53.486 to "cincuenta y tres punto cuatro ocho seis",
        55 to "cincuenta y cinco",
        60 to "sesenta",
        67 to "sesenta y siete",
        70 to "setenta",
        79 to "setenta y nueve",
        89 to "ochenta y nueve",
        95 to "noventa y cinco",
        100 to "cien",
        101 to "ciento uno",
        199 to "ciento noventa y nueve",
        203 to "doscientos tres",
        287 to "doscientos ochenta y siete",
        300.42 to "trescientos punto cuatro dos",
        356 to "trescientos cincuenta y seis",
        400 to "cuatrocientos",
        434 to "cuatrocientos treinta y cuatro",
        578 to "quinientos setenta y ocho",
        689 to "seiscientos ochenta y nueve",
        729 to "setecientos veintinueve",
        894 to "ochocientos noventa y cuatro",
        999 to "novecientos noventa y nueve",
        1000 to "mil",
        1001 to "mil uno",
        1097 to "mil noventa y siete",
        1104 to "mil ciento cuatro",
        1243 to "mil doscientos cuarenta y tres",
        2385 to "dos mil trescientos ochenta y cinco",
        3766 to "tres mil setecientos sesenta y seis",
        4196 to "cuatro mil ciento noventa y seis",
        4196.42 to "cuatro mil ciento noventa y seis punto cuatro dos",
        5846 to "cinco mil ochocientos cuarenta y seis",
        6459 to "seis mil cuatrocientos cincuenta y nueve",
        7232 to "siete mil doscientos treinta y dos",
        8569 to "ocho mil quinientos sesenta y nueve",
        9539 to "nueve mil quinientos treinta y nueve",
        1000000 to "un millón",
        1000001 to "un millón uno",
        4000000 to "cuatro millones",
        10000000000000 to "diez billones",
        100000000000000 to "cien billones",
        1000000000000000000 to "un trillón",
        "1000000000000000000000" to "mil trillones",
        "10000000000000000000000000" to "diez cuatrillones",
    )
    private val ORDINAL = listOf<Pair<Number, String>>(
        1 to "primero",
        8 to "octavo",
        12 to "decimosegundo",
        14 to "decimocuarto",
        28 to "vigesimoctavo",
        48 to "cuadragésimo octavo",
        100 to "centésimo",
        1000 to "milésimo",
        12345 to "docemilésimo tricentésimo cuadragésimo quinto",
        1000000 to "millonésimo",
        1000000000000000 to "cuadrillonésimo",
        1000000000000000000 to "un trillón",
    )
    private val ORDINAL_FEM = listOf<Pair<Number, String>>(
        1 to "primera",
        8 to "octava",
        12 to "decimosegunda",
        14 to "decimocuarta",
        28 to "vigesimoctava",
        48 to "cuadragésima octava",
        100 to "centésima",
        1000 to "milésima",
        12345 to "docemilésima tricentésima cuadragésima quinta",
        1000000 to "millonésima",
        1000000000000000 to "cuadrillonésima",
        1000000000000000000 to "un trillón",
    )
    private val ORDINAL_NUM = listOf<Pair<Number, String>>(
        1 to "1º",
        8 to "8º",
        12 to "12º",
        14 to "14º",
        28 to "28º",
        100 to "100º",
        1000 to "1000º",
        1000000 to "1000000º",
    )
    private val TEST_CASES_TO_CURRENCY = listOf<Pair<Any, String>>(
        1.0 to "un euro con cero céntimos",
        1.01 to "un euro con un céntimo",
        2.0 to "dos euros con cero céntimos",
        8.0 to "ocho euros con cero céntimos",
        12.0 to "doce euros con cero céntimos",
        21.0 to "veintiún euros con cero céntimos",
        81.25 to "ochenta y un euros con veinticinco céntimos",
        350.9 to "trescientos cincuenta euros con noventa céntimos",
        100.0 to "cien euros con cero céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_AED = listOf<Pair<Any, String>>(
        1.0 to "un dirham con cero fils",
        2.0 to "dos dirhams con cero fils",
        8.0 to "ocho dirhams con cero fils",
        12.0 to "doce dirhams con cero fils",
        21.0 to "veintiún dirhams con cero fils",
        81.25 to "ochenta y un dirhams con veinticinco fils",
        350.9 to "trescientos cincuenta dirhams con noventa fils",
        100.0 to "cien dirhams con cero fils",
        4150.83 to "cuatro mil ciento cincuenta dirhams con ochenta y tres fils",
    )
    private val TEST_CASES_TO_CURRENCY_AFN = listOf<Pair<Any, String>>(
        1.0 to "un afghani con cero puls",
        2.0 to "dos afghanis con cero puls",
        8.0 to "ocho afghanis con cero puls",
        12.0 to "doce afghanis con cero puls",
        21.0 to "veintiún afghanis con cero puls",
        81.25 to "ochenta y un afghanis con veinticinco puls",
        350.9 to "trescientos cincuenta afghanis con noventa puls",
        100.0 to "cien afghanis con cero puls",
        4150.83 to "cuatro mil ciento cincuenta afghanis con ochenta y tres puls",
    )
    private val TEST_CASES_TO_CURRENCY_ALL = listOf<Pair<Any, String>>(
        1.0 to "un lek  con cero qindarka",
        2.0 to "dos leke con cero qindarka",
        8.0 to "ocho leke con cero qindarka",
        12.0 to "doce leke con cero qindarka",
        21.0 to "veintiún leke con cero qindarka",
        81.25 to "ochenta y un leke con veinticinco qindarka",
        350.9 to "trescientos cincuenta leke con noventa qindarka",
        100.0 to "cien leke con cero qindarka",
        4150.83 to "cuatro mil ciento cincuenta leke con ochenta y tres qindarka",
    )
    private val TEST_CASES_TO_CURRENCY_AMD = listOf<Pair<Any, String>>(
        1.0 to "un dram con cero lumas",
        2.0 to "dos drams con cero lumas",
        8.0 to "ocho drams con cero lumas",
        12.0 to "doce drams con cero lumas",
        21.0 to "veintiún drams con cero lumas",
        81.25 to "ochenta y un drams con veinticinco lumas",
        350.9 to "trescientos cincuenta drams con noventa lumas",
        100.0 to "cien drams con cero lumas",
        4150.83 to "cuatro mil ciento cincuenta drams con ochenta y tres lumas",
    )
    private val TEST_CASES_TO_CURRENCY_ANG = listOf<Pair<Any, String>>(
        1.0 to "un florín con cero centavos",
        2.0 to "dos florines con cero centavos",
        8.0 to "ocho florines con cero centavos",
        12.0 to "doce florines con cero centavos",
        21.0 to "veintiún florines con cero centavos",
        81.25 to "ochenta y un florines con veinticinco centavos",
        350.9 to "trescientos cincuenta florines con noventa centavos",
        100.0 to "cien florines con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta florines con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_AOA = listOf<Pair<Any, String>>(
        1.0 to "un kwanza con cero céntimos",
        2.0 to "dos kwanzas con cero céntimos",
        8.0 to "ocho kwanzas con cero céntimos",
        12.0 to "doce kwanzas con cero céntimos",
        21.0 to "veintiún kwanzas con cero céntimos",
        81.25 to "ochenta y un kwanzas con veinticinco céntimos",
        350.9 to "trescientos cincuenta kwanzas con noventa céntimos",
        100.0 to "cien kwanzas con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta kwanzas con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_AWG = listOf<Pair<Any, String>>(
        1.0 to "un florín con cero centavos",
        2.0 to "dos florines con cero centavos",
        8.0 to "ocho florines con cero centavos",
        12.0 to "doce florines con cero centavos",
        21.0 to "veintiún florines con cero centavos",
        81.25 to "ochenta y un florines con veinticinco centavos",
        350.9 to "trescientos cincuenta florines con noventa centavos",
        100.0 to "cien florines con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta florines con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_AZN = listOf<Pair<Any, String>>(
        1.0 to "un manat con cero qəpik",
        2.0 to "dos manat con cero qəpik",
        8.0 to "ocho manat con cero qəpik",
        12.0 to "doce manat con cero qəpik",
        21.0 to "veintiún manat con cero qəpik",
        81.25 to "ochenta y un manat con veinticinco qəpik",
        350.9 to "trescientos cincuenta manat con noventa qəpik",
        100.0 to "cien manat con cero qəpik",
        4150.83 to "cuatro mil ciento cincuenta manat con ochenta y tres qəpik",
    )
    private val TEST_CASES_TO_CURRENCY_BDT = listOf<Pair<Any, String>>(
        1.0 to "un taka con cero paisas",
        2.0 to "dos takas con cero paisas",
        8.0 to "ocho takas con cero paisas",
        12.0 to "doce takas con cero paisas",
        21.0 to "veintiún takas con cero paisas",
        81.25 to "ochenta y un takas con veinticinco paisas",
        350.9 to "trescientos cincuenta takas con noventa paisas",
        100.0 to "cien takas con cero paisas",
        4150.83 to "cuatro mil ciento cincuenta takas con ochenta y tres paisas",
    )
    private val TEST_CASES_TO_CURRENCY_BGN = listOf<Pair<Any, String>>(
        1.0 to "un lev con cero stotinki",
        2.0 to "dos leva con cero stotinki",
        8.0 to "ocho leva con cero stotinki",
        12.0 to "doce leva con cero stotinki",
        21.0 to "veintiún leva con cero stotinki",
        81.25 to "ochenta y un leva con veinticinco stotinki",
        350.9 to "trescientos cincuenta leva con noventa stotinki",
        100.0 to "cien leva con cero stotinki",
        4150.83 to "cuatro mil ciento cincuenta leva con ochenta y tres stotinki",
    )
    private val TEST_CASES_TO_CURRENCY_BHD = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero fils",
        2.0 to "dos dinares con cero fils",
        8.0 to "ocho dinares con cero fils",
        12.0 to "doce dinares con cero fils",
        21.0 to "veintiún dinares con cero fils",
        81.25 to "ochenta y un dinares con veinticinco fils",
        350.9 to "trescientos cincuenta dinares con noventa fils",
        100.0 to "cien dinares con cero fils",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres fils",
    )
    private val TEST_CASES_TO_CURRENCY_BOB = listOf<Pair<Any, String>>(
        1.0 to "un boliviano con cero centavos",
        2.0 to "dos bolivianos con cero centavos",
        8.0 to "ocho bolivianos con cero centavos",
        12.0 to "doce bolivianos con cero centavos",
        21.0 to "veintiún bolivianos con cero centavos",
        81.25 to "ochenta y un bolivianos con veinticinco centavos",
        350.9 to "trescientos cincuenta bolivianos con noventa centavos",
        100.0 to "cien bolivianos con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta bolivianos con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_BRL = listOf<Pair<Any, String>>(
        1.0 to "un real con cero centavos",
        2.0 to "dos reales con cero centavos",
        8.0 to "ocho reales con cero centavos",
        12.0 to "doce reales con cero centavos",
        21.0 to "veintiún reales con cero centavos",
        81.25 to "ochenta y un reales con veinticinco centavos",
        350.9 to "trescientos cincuenta reales con noventa centavos",
        100.0 to "cien reales con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta reales con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_BTN = listOf<Pair<Any, String>>(
        1.0 to "un ngultrum con cero chetrum",
        2.0 to "dos ngultrum con cero chetrum",
        8.0 to "ocho ngultrum con cero chetrum",
        12.0 to "doce ngultrum con cero chetrum",
        21.0 to "veintiún ngultrum con cero chetrum",
        81.25 to "ochenta y un ngultrum con veinticinco chetrum",
        350.9 to "trescientos cincuenta ngultrum con noventa chetrum",
        100.0 to "cien ngultrum con cero chetrum",
        4150.83 to "cuatro mil ciento cincuenta ngultrum con ochenta y tres chetrum",
    )
    private val TEST_CASES_TO_CURRENCY_BWP = listOf<Pair<Any, String>>(
        1.0 to "un pula con cero thebes",
        2.0 to "dos pulas con cero thebes",
        8.0 to "ocho pulas con cero thebes",
        12.0 to "doce pulas con cero thebes",
        21.0 to "veintiún pulas con cero thebes",
        81.25 to "ochenta y un pulas con veinticinco thebes",
        350.9 to "trescientos cincuenta pulas con noventa thebes",
        100.0 to "cien pulas con cero thebes",
        4150.83 to "cuatro mil ciento cincuenta pulas con ochenta y tres thebes",
    )
    private val TEST_CASES_TO_CURRENCY_BYN = listOf<Pair<Any, String>>(
        1.0 to "un rublo con cero kópeks",
        2.0 to "dos rublos con cero kópeks",
        8.0 to "ocho rublos con cero kópeks",
        12.0 to "doce rublos con cero kópeks",
        21.0 to "veintiún rublos con cero kópeks",
        81.25 to "ochenta y un rublos con veinticinco kópeks",
        350.9 to "trescientos cincuenta rublos con noventa kópeks",
        100.0 to "cien rublos con cero kópeks",
        4150.83 to "cuatro mil ciento cincuenta rublos con ochenta y tres kópeks",
    )
    private val TEST_CASES_TO_CURRENCY_BYR = listOf<Pair<Any, String>>(
        1.0 to "un rublo con cero kópeks",
        2.0 to "dos rublos con cero kópeks",
        8.0 to "ocho rublos con cero kópeks",
        12.0 to "doce rublos con cero kópeks",
        21.0 to "veintiún rublos con cero kópeks",
        81.25 to "ochenta y un rublos con veinticinco kópeks",
        350.9 to "trescientos cincuenta rublos con noventa kópeks",
        100.0 to "cien rublos con cero kópeks",
        4150.83 to "cuatro mil ciento cincuenta rublos con ochenta y tres kópeks",
    )
    private val TEST_CASES_TO_CURRENCY_BZD = listOf<Pair<Any, String>>(
        1.0 to "un dólar con cero céntimos",
        2.0 to "dos dólares con cero céntimos",
        8.0 to "ocho dólares con cero céntimos",
        12.0 to "doce dólares con cero céntimos",
        21.0 to "veintiún dólares con cero céntimos",
        81.25 to "ochenta y un dólares con veinticinco céntimos",
        350.9 to "trescientos cincuenta dólares con noventa céntimos",
        100.0 to "cien dólares con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta dólares con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_CNY = listOf<Pair<Any, String>>(
        1.0 to "un yuan con cero jiaos",
        2.0 to "dos yuanes con cero jiaos",
        8.0 to "ocho yuanes con cero jiaos",
        12.0 to "doce yuanes con cero jiaos",
        21.0 to "veintiún yuanes con cero jiaos",
        81.25 to "ochenta y un yuanes con veinticinco jiaos",
        350.9 to "trescientos cincuenta yuanes con noventa jiaos",
        100.0 to "cien yuanes con cero jiaos",
        4150.83 to "cuatro mil ciento cincuenta yuanes con ochenta y tres jiaos",
    )
    private val TEST_CASES_TO_CURRENCY_CRC = listOf<Pair<Any, String>>(
        1.0 to "un colón con cero centavos",
        2.0 to "dos colones con cero centavos",
        8.0 to "ocho colones con cero centavos",
        12.0 to "doce colones con cero centavos",
        21.0 to "veintiún colones con cero centavos",
        81.25 to "ochenta y un colones con veinticinco centavos",
        350.9 to "trescientos cincuenta colones con noventa centavos",
        100.0 to "cien colones con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta colones con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_CVE = listOf<Pair<Any, String>>(
        1.0 to "un escudo con cero centavos",
        2.0 to "dos escudos con cero centavos",
        8.0 to "ocho escudos con cero centavos",
        12.0 to "doce escudos con cero centavos",
        21.0 to "veintiún escudos con cero centavos",
        81.25 to "ochenta y un escudos con veinticinco centavos",
        350.9 to "trescientos cincuenta escudos con noventa centavos",
        100.0 to "cien escudos con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta escudos con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_CYP = listOf<Pair<Any, String>>(
        1.0 to "una libra con cero céntimos",
        2.0 to "dos libras con cero céntimos",
        8.0 to "ocho libras con cero céntimos",
        12.0 to "doce libras con cero céntimos",
        21.0 to "veintiuna libras con cero céntimos",
        81.25 to "ochenta y una libras con veinticinco céntimos",
        350.9 to "trescientas cincuenta libras con noventa céntimos",
        100.0 to "cien libras con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta libras con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_CZK = listOf<Pair<Any, String>>(
        1.0 to "una corona con cero haléř",
        2.0 to "dos coronas con cero haléř",
        8.0 to "ocho coronas con cero haléř",
        12.0 to "doce coronas con cero haléř",
        21.0 to "veintiuna coronas con cero haléř",
        81.25 to "ochenta y una coronas con veinticinco haléř",
        350.9 to "trescientas cincuenta coronas con noventa haléř",
        100.0 to "cien coronas con cero haléř",
        4150.83 to "cuatro mil ciento cincuenta coronas con ochenta y tres haléř",
    )
    private val TEST_CASES_TO_CURRENCY_DKK = listOf<Pair<Any, String>>(
        1.0 to "una corona con cero øre",
        2.0 to "dos coronas con cero øre",
        8.0 to "ocho coronas con cero øre",
        12.0 to "doce coronas con cero øre",
        21.0 to "veintiuna coronas con cero øre",
        81.25 to "ochenta y una coronas con veinticinco øre",
        350.9 to "trescientas cincuenta coronas con noventa øre",
        100.0 to "cien coronas con cero øre",
        4150.83 to "cuatro mil ciento cincuenta coronas con ochenta y tres øre",
    )
    private val TEST_CASES_TO_CURRENCY_DZD = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero céntimos",
        2.0 to "dos dinares con cero céntimos",
        8.0 to "ocho dinares con cero céntimos",
        12.0 to "doce dinares con cero céntimos",
        21.0 to "veintiún dinares con cero céntimos",
        81.25 to "ochenta y un dinares con veinticinco céntimos",
        350.9 to "trescientos cincuenta dinares con noventa céntimos",
        100.0 to "cien dinares con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_ECS = listOf<Pair<Any, String>>(
        1.0 to "un sucre con cero centavos",
        2.0 to "dos sucres con cero centavos",
        8.0 to "ocho sucres con cero centavos",
        12.0 to "doce sucres con cero centavos",
        21.0 to "veintiún sucres con cero centavos",
        81.25 to "ochenta y un sucres con veinticinco centavos",
        350.9 to "trescientos cincuenta sucres con noventa centavos",
        100.0 to "cien sucres con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta sucres con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_EGP = listOf<Pair<Any, String>>(
        1.0 to "una libra con cero piastras",
        2.0 to "dos libras con cero piastras",
        8.0 to "ocho libras con cero piastras",
        12.0 to "doce libras con cero piastras",
        21.0 to "veintiuna libras con cero piastras",
        81.21 to "ochenta y una libras con veintiuna piastras",
        81.25 to "ochenta y una libras con veinticinco piastras",
        350.9 to "trescientas cincuenta libras con noventa piastras",
        100.0 to "cien libras con cero piastras",
        4150.83 to "cuatro mil ciento cincuenta libras con ochenta y tres piastras",
    )
    private val TEST_CASES_TO_CURRENCY_ERN = listOf<Pair<Any, String>>(
        1.0 to "un nakfa con cero céntimos",
        2.0 to "dos nakfas con cero céntimos",
        8.0 to "ocho nakfas con cero céntimos",
        12.0 to "doce nakfas con cero céntimos",
        21.0 to "veintiún nakfas con cero céntimos",
        81.25 to "ochenta y un nakfas con veinticinco céntimos",
        350.9 to "trescientos cincuenta nakfas con noventa céntimos",
        100.0 to "cien nakfas con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta nakfas con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_ESP = listOf<Pair<Any, String>>(
        1.0 to "una peseta con cero céntimos",
        1.01 to "una peseta con un céntimo",
        2.0 to "dos pesetas con cero céntimos",
        8.0 to "ocho pesetas con cero céntimos",
        12.0 to "doce pesetas con cero céntimos",
        21.0 to "veintiuna pesetas con cero céntimos",
        81.25 to "ochenta y una pesetas con veinticinco céntimos",
        350.9 to "trescientas cincuenta pesetas con noventa céntimos",
        100.0 to "cien pesetas con cero céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_ETB = listOf<Pair<Any, String>>(
        1.0 to "un birr con cero céntimos",
        2.0 to "dos birrs con cero céntimos",
        8.0 to "ocho birrs con cero céntimos",
        12.0 to "doce birrs con cero céntimos",
        21.0 to "veintiún birrs con cero céntimos",
        81.25 to "ochenta y un birrs con veinticinco céntimos",
        350.9 to "trescientos cincuenta birrs con noventa céntimos",
        100.0 to "cien birrs con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta birrs con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_FKP = listOf<Pair<Any, String>>(
        1.0 to "una libra con cero peniques",
        2.0 to "dos libras con cero peniques",
        8.0 to "ocho libras con cero peniques",
        12.0 to "doce libras con cero peniques",
        21.0 to "veintiuna libras con cero peniques",
        81.25 to "ochenta y una libras con veinticinco peniques",
        350.9 to "trescientas cincuenta libras con noventa peniques",
        100.0 to "cien libras con cero peniques",
        4150.83 to "cuatro mil ciento cincuenta libras con ochenta y tres peniques",
    )
    private val TEST_CASES_TO_CURRENCY_FRF = listOf<Pair<Any, String>>(
        1.0 to "un franco con cero céntimos",
        2.0 to "dos francos con cero céntimos",
        8.0 to "ocho francos con cero céntimos",
        12.0 to "doce francos con cero céntimos",
        21.0 to "veintiún francos con cero céntimos",
        81.25 to "ochenta y un francos con veinticinco céntimos",
        350.9 to "trescientos cincuenta francos con noventa céntimos",
        100.0 to "cien francos con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta francos con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_GBP = listOf<Pair<Any, String>>(
        1.0 to "una libra con cero peniques",
        1.01 to "una libra con un penique",
        2.0 to "dos libras con cero peniques",
        8.0 to "ocho libras con cero peniques",
        12.0 to "doce libras con cero peniques",
        21.0 to "veintiuna libras con cero peniques",
        81.25 to "ochenta y una libras con veinticinco peniques",
        350.9 to "trescientas cincuenta libras con noventa peniques",
        100.0 to "cien libras con cero peniques",
        4150.83 to "cuatro mil ciento cincuenta libras con ochenta y tres peniques",
    )
    private val TEST_CASES_TO_CURRENCY_GEL = listOf<Pair<Any, String>>(
        1.0 to "un lari con cero tetris",
        2.0 to "dos laris con cero tetris",
        8.0 to "ocho laris con cero tetris",
        12.0 to "doce laris con cero tetris",
        21.0 to "veintiún laris con cero tetris",
        81.25 to "ochenta y un laris con veinticinco tetris",
        350.9 to "trescientos cincuenta laris con noventa tetris",
        100.0 to "cien laris con cero tetris",
        4150.83 to "cuatro mil ciento cincuenta laris con ochenta y tres tetris",
    )
    private val TEST_CASES_TO_CURRENCY_GHS = listOf<Pair<Any, String>>(
        1.0 to "un cedi con cero pesewas",
        2.0 to "dos cedis con cero pesewas",
        8.0 to "ocho cedis con cero pesewas",
        12.0 to "doce cedis con cero pesewas",
        21.0 to "veintiún cedis con cero pesewas",
        81.25 to "ochenta y un cedis con veinticinco pesewas",
        350.9 to "trescientos cincuenta cedis con noventa pesewas",
        100.0 to "cien cedis con cero pesewas",
        4150.83 to "cuatro mil ciento cincuenta cedis con ochenta y tres pesewas",
    )
    private val TEST_CASES_TO_CURRENCY_GMD = listOf<Pair<Any, String>>(
        1.0 to "un dalasi con cero bututs",
        2.0 to "dos dalasis con cero bututs",
        8.0 to "ocho dalasis con cero bututs",
        12.0 to "doce dalasis con cero bututs",
        21.0 to "veintiún dalasis con cero bututs",
        81.25 to "ochenta y un dalasis con veinticinco bututs",
        350.9 to "trescientos cincuenta dalasis con noventa bututs",
        100.0 to "cien dalasis con cero bututs",
        4150.83 to "cuatro mil ciento cincuenta dalasis con ochenta y tres bututs",
    )
    private val TEST_CASES_TO_CURRENCY_GTQ = listOf<Pair<Any, String>>(
        1.0 to "un quetzal con cero centavos",
        2.0 to "dos quetzales con cero centavos",
        8.0 to "ocho quetzales con cero centavos",
        12.0 to "doce quetzales con cero centavos",
        21.0 to "veintiún quetzales con cero centavos",
        81.25 to "ochenta y un quetzales con veinticinco centavos",
        350.9 to "trescientos cincuenta quetzales con noventa centavos",
        100.0 to "cien quetzales con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta quetzales con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_HNL = listOf<Pair<Any, String>>(
        1.0 to "un lempira con cero centavos",
        2.0 to "dos lempiras con cero centavos",
        8.0 to "ocho lempiras con cero centavos",
        12.0 to "doce lempiras con cero centavos",
        21.0 to "veintiún lempiras con cero centavos",
        81.25 to "ochenta y un lempiras con veinticinco centavos",
        350.9 to "trescientos cincuenta lempiras con noventa centavos",
        100.0 to "cien lempiras con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta lempiras con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_HRK = listOf<Pair<Any, String>>(
        1.0 to "un kuna con cero lipas",
        2.0 to "dos kunas con cero lipas",
        8.0 to "ocho kunas con cero lipas",
        12.0 to "doce kunas con cero lipas",
        21.0 to "veintiún kunas con cero lipas",
        81.25 to "ochenta y un kunas con veinticinco lipas",
        350.9 to "trescientos cincuenta kunas con noventa lipas",
        100.0 to "cien kunas con cero lipas",
        4150.83 to "cuatro mil ciento cincuenta kunas con ochenta y tres lipas",
    )
    private val TEST_CASES_TO_CURRENCY_HTG = listOf<Pair<Any, String>>(
        1.0 to "un gourde con cero céntimos",
        2.0 to "dos gourdes con cero céntimos",
        8.0 to "ocho gourdes con cero céntimos",
        12.0 to "doce gourdes con cero céntimos",
        21.0 to "veintiún gourdes con cero céntimos",
        81.25 to "ochenta y un gourdes con veinticinco céntimos",
        350.9 to "trescientos cincuenta gourdes con noventa céntimos",
        100.0 to "cien gourdes con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta gourdes con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_HUF = listOf<Pair<Any, String>>(
        1.0 to "un florín con cero fillér",
        2.0 to "dos florines con cero fillér",
        8.0 to "ocho florines con cero fillér",
        12.0 to "doce florines con cero fillér",
        21.0 to "veintiún florines con cero fillér",
        81.25 to "ochenta y un florines con veinticinco fillér",
        350.9 to "trescientos cincuenta florines con noventa fillér",
        100.0 to "cien florines con cero fillér",
        4150.83 to "cuatro mil ciento cincuenta florines con ochenta y tres fillér",
    )
    private val TEST_CASES_TO_CURRENCY_IDR = listOf<Pair<Any, String>>(
        1.0 to "una rupia con cero céntimos",
        2.0 to "dos rupias con cero céntimos",
        8.0 to "ocho rupias con cero céntimos",
        12.0 to "doce rupias con cero céntimos",
        21.0 to "veintiuna rupias con cero céntimos",
        81.25 to "ochenta y una rupias con veinticinco céntimos",
        350.9 to "trescientas cincuenta rupias con noventa céntimos",
        100.0 to "cien rupias con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta rupias con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_ILS = listOf<Pair<Any, String>>(
        1.0 to "un séquel con cero agoras",
        2.0 to "dos séqueles con cero agoras",
        8.0 to "ocho séqueles con cero agoras",
        12.0 to "doce séqueles con cero agoras",
        21.0 to "veintiún séqueles con cero agoras",
        81.25 to "ochenta y un séqueles con veinticinco agoras",
        350.9 to "trescientos cincuenta séqueles con noventa agoras",
        100.0 to "cien séqueles con cero agoras",
        4150.83 to "cuatro mil ciento cincuenta séqueles con ochenta y tres agoras",
    )
    private val TEST_CASES_TO_CURRENCY_INR = listOf<Pair<Any, String>>(
        1.0 to "una rupia con cero paisas",
        2.0 to "dos rupias con cero paisas",
        8.0 to "ocho rupias con cero paisas",
        12.0 to "doce rupias con cero paisas",
        21.0 to "veintiuna rupias con cero paisas",
        81.25 to "ochenta y una rupias con veinticinco paisas",
        350.9 to "trescientas cincuenta rupias con noventa paisas",
        100.0 to "cien rupias con cero paisas",
        4150.83 to "cuatro mil ciento cincuenta rupias con ochenta y tres paisas",
    )
    private val TEST_CASES_TO_CURRENCY_IQD = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero fils",
        2.0 to "dos dinares con cero fils",
        8.0 to "ocho dinares con cero fils",
        12.0 to "doce dinares con cero fils",
        21.0 to "veintiún dinares con cero fils",
        81.25 to "ochenta y un dinares con veinticinco fils",
        350.9 to "trescientos cincuenta dinares con noventa fils",
        100.0 to "cien dinares con cero fils",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres fils",
    )
    private val TEST_CASES_TO_CURRENCY_IRR = listOf<Pair<Any, String>>(
        1.0 to "un rial con cero dinares",
        2.0 to "dos riales con cero dinares",
        8.0 to "ocho riales con cero dinares",
        12.0 to "doce riales con cero dinares",
        21.0 to "veintiún riales con cero dinares",
        81.25 to "ochenta y un riales con veinticinco dinares",
        350.9 to "trescientos cincuenta riales con noventa dinares",
        100.0 to "cien riales con cero dinares",
        4150.83 to "cuatro mil ciento cincuenta riales con ochenta y tres dinares",
    )
    private val TEST_CASES_TO_CURRENCY_ISK = listOf<Pair<Any, String>>(
        1.0 to "una corona con cero aurar",
        2.0 to "dos coronas con cero aurar",
        8.0 to "ocho coronas con cero aurar",
        12.0 to "doce coronas con cero aurar",
        21.0 to "veintiuna coronas con cero aurar",
        81.25 to "ochenta y una coronas con veinticinco aurar",
        350.9 to "trescientas cincuenta coronas con noventa aurar",
        100.0 to "cien coronas con cero aurar",
        4150.83 to "cuatro mil ciento cincuenta coronas con ochenta y tres aurar",
    )
    private val TEST_CASES_TO_CURRENCY_ITL = listOf<Pair<Any, String>>(
        1.0 to "una lira con cero céntimos",
        2.0 to "dos liras con cero céntimos",
        8.0 to "ocho liras con cero céntimos",
        12.0 to "doce liras con cero céntimos",
        21.0 to "veintiuna liras con cero céntimos",
        81.25 to "ochenta y una liras con veinticinco céntimos",
        350.9 to "trescientas cincuenta liras con noventa céntimos",
        100.0 to "cien liras con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta liras con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_JOD = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero piastras",
        2.0 to "dos dinares con cero piastras",
        8.0 to "ocho dinares con cero piastras",
        12.0 to "doce dinares con cero piastras",
        21.0 to "veintiún dinares con cero piastras",
        81.25 to "ochenta y un dinares con veinticinco piastras",
        350.9 to "trescientos cincuenta dinares con noventa piastras",
        100.0 to "cien dinares con cero piastras",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres piastras",
    )
    private val TEST_CASES_TO_CURRENCY_JPY = listOf<Pair<Any, String>>(
        1.0 to "un yen con cero sen",
        2.0 to "dos yenes con cero sen",
        8.0 to "ocho yenes con cero sen",
        12.0 to "doce yenes con cero sen",
        21.0 to "veintiún yenes con cero sen",
        81.25 to "ochenta y un yenes con veinticinco sen",
        350.9 to "trescientos cincuenta yenes con noventa sen",
        100.0 to "cien yenes con cero sen",
        4150.83 to "cuatro mil ciento cincuenta yenes con ochenta y tres sen",
    )
    private val TEST_CASES_TO_CURRENCY_KES = listOf<Pair<Any, String>>(
        1.0 to "un chelín con cero céntimos",
        2.0 to "dos chelines con cero céntimos",
        8.0 to "ocho chelines con cero céntimos",
        12.0 to "doce chelines con cero céntimos",
        21.0 to "veintiún chelines con cero céntimos",
        81.25 to "ochenta y un chelines con veinticinco céntimos",
        350.9 to "trescientos cincuenta chelines con noventa céntimos",
        100.0 to "cien chelines con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta chelines con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_KGS = listOf<Pair<Any, String>>(
        1.0 to "un som con cero tyiyn",
        2.0 to "dos som con cero tyiyn",
        8.0 to "ocho som con cero tyiyn",
        12.0 to "doce som con cero tyiyn",
        21.0 to "veintiún som con cero tyiyn",
        81.25 to "ochenta y un som con veinticinco tyiyn",
        350.9 to "trescientos cincuenta som con noventa tyiyn",
        100.0 to "cien som con cero tyiyn",
        4150.83 to "cuatro mil ciento cincuenta som con ochenta y tres tyiyn",
    )
    private val TEST_CASES_TO_CURRENCY_KHR = listOf<Pair<Any, String>>(
        1.0 to "un riel con cero céntimos",
        2.0 to "dos rieles con cero céntimos",
        8.0 to "ocho rieles con cero céntimos",
        12.0 to "doce rieles con cero céntimos",
        21.0 to "veintiún rieles con cero céntimos",
        81.25 to "ochenta y un rieles con veinticinco céntimos",
        350.9 to "trescientos cincuenta rieles con noventa céntimos",
        100.0 to "cien rieles con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta rieles con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_KPW = listOf<Pair<Any, String>>(
        1.0 to "un won con cero chon",
        2.0 to "dos wones con cero chon",
        8.0 to "ocho wones con cero chon",
        12.0 to "doce wones con cero chon",
        21.0 to "veintiún wones con cero chon",
        81.25 to "ochenta y un wones con veinticinco chon",
        350.9 to "trescientos cincuenta wones con noventa chon",
        100.0 to "cien wones con cero chon",
        4150.83 to "cuatro mil ciento cincuenta wones con ochenta y tres chon",
    )
    private val TEST_CASES_TO_CURRENCY_KRW = listOf<Pair<Any, String>>(
        1.0 to "un won con cero jeon",
        2.0 to "dos wones con cero jeon",
        8.0 to "ocho wones con cero jeon",
        12.0 to "doce wones con cero jeon",
        21.0 to "veintiún wones con cero jeon",
        81.25 to "ochenta y un wones con veinticinco jeon",
        350.9 to "trescientos cincuenta wones con noventa jeon",
        100.0 to "cien wones con cero jeon",
        4150.83 to "cuatro mil ciento cincuenta wones con ochenta y tres jeon",
    )
    private val TEST_CASES_TO_CURRENCY_KWD = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero fils",
        2.0 to "dos dinares con cero fils",
        8.0 to "ocho dinares con cero fils",
        12.0 to "doce dinares con cero fils",
        21.0 to "veintiún dinares con cero fils",
        81.25 to "ochenta y un dinares con veinticinco fils",
        350.9 to "trescientos cincuenta dinares con noventa fils",
        100.0 to "cien dinares con cero fils",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres fils",
    )
    private val TEST_CASES_TO_CURRENCY_KZT = listOf<Pair<Any, String>>(
        1.0 to "un tenge con cero tïın",
        2.0 to "dos tenges con cero tïın",
        8.0 to "ocho tenges con cero tïın",
        12.0 to "doce tenges con cero tïın",
        21.0 to "veintiún tenges con cero tïın",
        81.25 to "ochenta y un tenges con veinticinco tïın",
        350.9 to "trescientos cincuenta tenges con noventa tïın",
        100.0 to "cien tenges con cero tïın",
        4150.83 to "cuatro mil ciento cincuenta tenges con ochenta y tres tïın",
    )
    private val TEST_CASES_TO_CURRENCY_LAK = listOf<Pair<Any, String>>(
        1.0 to "un kip con cero att",
        2.0 to "dos kips con cero att",
        8.0 to "ocho kips con cero att",
        12.0 to "doce kips con cero att",
        21.0 to "veintiún kips con cero att",
        81.25 to "ochenta y un kips con veinticinco att",
        350.9 to "trescientos cincuenta kips con noventa att",
        100.0 to "cien kips con cero att",
        4150.83 to "cuatro mil ciento cincuenta kips con ochenta y tres att",
    )
    private val TEST_CASES_TO_CURRENCY_LKR = listOf<Pair<Any, String>>(
        1.0 to "una rupia con cero céntimos",
        2.0 to "dos rupias con cero céntimos",
        8.0 to "ocho rupias con cero céntimos",
        12.0 to "doce rupias con cero céntimos",
        21.0 to "veintiuna rupias con cero céntimos",
        81.25 to "ochenta y una rupias con veinticinco céntimos",
        350.9 to "trescientas cincuenta rupias con noventa céntimos",
        100.0 to "cien rupias con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta rupias con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_LSL = listOf<Pair<Any, String>>(
        1.0 to "un loti con cero céntimos",
        2.0 to "dos lotis con cero céntimos",
        8.0 to "ocho lotis con cero céntimos",
        12.0 to "doce lotis con cero céntimos",
        21.0 to "veintiún lotis con cero céntimos",
        81.25 to "ochenta y un lotis con veinticinco céntimos",
        350.9 to "trescientos cincuenta lotis con noventa céntimos",
        100.0 to "cien lotis con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta lotis con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_LTL = listOf<Pair<Any, String>>(
        1.0 to "un lita con cero céntimos",
        2.0 to "dos litas con cero céntimos",
        8.0 to "ocho litas con cero céntimos",
        12.0 to "doce litas con cero céntimos",
        21.0 to "veintiún litas con cero céntimos",
        81.25 to "ochenta y un litas con veinticinco céntimos",
        350.9 to "trescientos cincuenta litas con noventa céntimos",
        100.0 to "cien litas con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta litas con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_LVL = listOf<Pair<Any, String>>(
        1.0 to "un lat con cero céntimos",
        2.0 to "dos lats con cero céntimos",
        8.0 to "ocho lats con cero céntimos",
        12.0 to "doce lats con cero céntimos",
        21.0 to "veintiún lats con cero céntimos",
        81.25 to "ochenta y un lats con veinticinco céntimos",
        350.9 to "trescientos cincuenta lats con noventa céntimos",
        100.0 to "cien lats con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta lats con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_LYD = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero dírhams",
        2.0 to "dos dinares con cero dírhams",
        8.0 to "ocho dinares con cero dírhams",
        12.0 to "doce dinares con cero dírhams",
        21.0 to "veintiún dinares con cero dírhams",
        81.25 to "ochenta y un dinares con veinticinco dírhams",
        350.9 to "trescientos cincuenta dinares con noventa dírhams",
        100.0 to "cien dinares con cero dírhams",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres dírhams",
    )
    private val TEST_CASES_TO_CURRENCY_MAD = listOf<Pair<Any, String>>(
        1.0 to "un dírham con cero céntimos",
        2.0 to "dos dirhams con cero céntimos",
        8.0 to "ocho dirhams con cero céntimos",
        12.0 to "doce dirhams con cero céntimos",
        21.0 to "veintiún dirhams con cero céntimos",
        81.25 to "ochenta y un dirhams con veinticinco céntimos",
        350.9 to "trescientos cincuenta dirhams con noventa céntimos",
        100.0 to "cien dirhams con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta dirhams con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_MDL = listOf<Pair<Any, String>>(
        1.0 to "un leu con cero bani",
        2.0 to "dos lei con cero bani",
        8.0 to "ocho lei con cero bani",
        12.0 to "doce lei con cero bani",
        21.0 to "veintiún lei con cero bani",
        81.25 to "ochenta y un lei con veinticinco bani",
        350.9 to "trescientos cincuenta lei con noventa bani",
        100.0 to "cien lei con cero bani",
        4150.83 to "cuatro mil ciento cincuenta lei con ochenta y tres bani",
    )
    private val TEST_CASES_TO_CURRENCY_MGA = listOf<Pair<Any, String>>(
        1.0 to "un ariary con cero iraimbilanja",
        2.0 to "dos ariaris con cero iraimbilanja",
        8.0 to "ocho ariaris con cero iraimbilanja",
        12.0 to "doce ariaris con cero iraimbilanja",
        21.0 to "veintiún ariaris con cero iraimbilanja",
        81.25 to "ochenta y un ariaris con veinticinco iraimbilanja",
        350.9 to "trescientos cincuenta ariaris con noventa iraimbilanja",
        100.0 to "cien ariaris con cero iraimbilanja",
        4150.83 to "cuatro mil ciento cincuenta ariaris con ochenta y tres iraimbilanja",
    )
    private val TEST_CASES_TO_CURRENCY_MKD = listOf<Pair<Any, String>>(
        1.0 to "un denar con cero denis",
        2.0 to "dos denares con cero denis",
        8.0 to "ocho denares con cero denis",
        12.0 to "doce denares con cero denis",
        21.0 to "veintiún denares con cero denis",
        81.25 to "ochenta y un denares con veinticinco denis",
        350.9 to "trescientos cincuenta denares con noventa denis",
        100.0 to "cien denares con cero denis",
        4150.83 to "cuatro mil ciento cincuenta denares con ochenta y tres denis",
    )
    private val TEST_CASES_TO_CURRENCY_MMK = listOf<Pair<Any, String>>(
        1.0 to "un kiat con cero pyas",
        2.0 to "dos kiats con cero pyas",
        8.0 to "ocho kiats con cero pyas",
        12.0 to "doce kiats con cero pyas",
        21.0 to "veintiún kiats con cero pyas",
        81.25 to "ochenta y un kiats con veinticinco pyas",
        350.9 to "trescientos cincuenta kiats con noventa pyas",
        100.0 to "cien kiats con cero pyas",
        4150.83 to "cuatro mil ciento cincuenta kiats con ochenta y tres pyas",
    )
    private val TEST_CASES_TO_CURRENCY_MNT = listOf<Pair<Any, String>>(
        1.0 to "un tugrik con cero möngö",
        2.0 to "dos tugriks con cero möngö",
        8.0 to "ocho tugriks con cero möngö",
        12.0 to "doce tugriks con cero möngö",
        21.0 to "veintiún tugriks con cero möngö",
        81.25 to "ochenta y un tugriks con veinticinco möngö",
        350.9 to "trescientos cincuenta tugriks con noventa möngö",
        100.0 to "cien tugriks con cero möngö",
        4150.83 to "cuatro mil ciento cincuenta tugriks con ochenta y tres möngö",
    )
    private val TEST_CASES_TO_CURRENCY_MOP = listOf<Pair<Any, String>>(
        1.0 to "un pataca con cero avos",
        2.0 to "dos patacas con cero avos",
        8.0 to "ocho patacas con cero avos",
        12.0 to "doce patacas con cero avos",
        21.0 to "veintiún patacas con cero avos",
        81.25 to "ochenta y un patacas con veinticinco avos",
        350.9 to "trescientos cincuenta patacas con noventa avos",
        100.0 to "cien patacas con cero avos",
        4150.83 to "cuatro mil ciento cincuenta patacas con ochenta y tres avos",
    )
    private val TEST_CASES_TO_CURRENCY_MRO = listOf<Pair<Any, String>>(
        1.0 to "un ouguiya con cero khoums",
        2.0 to "dos ouguiyas con cero khoums",
        8.0 to "ocho ouguiyas con cero khoums",
        12.0 to "doce ouguiyas con cero khoums",
        21.0 to "veintiún ouguiyas con cero khoums",
        81.25 to "ochenta y un ouguiyas con veinticinco khoums",
        350.9 to "trescientos cincuenta ouguiyas con noventa khoums",
        100.0 to "cien ouguiyas con cero khoums",
        4150.83 to "cuatro mil ciento cincuenta ouguiyas con ochenta y tres khoums",
    )
    private val TEST_CASES_TO_CURRENCY_MRU = listOf<Pair<Any, String>>(
        1.0 to "un ouguiya con cero khoums",
        2.0 to "dos ouguiyas con cero khoums",
        8.0 to "ocho ouguiyas con cero khoums",
        12.0 to "doce ouguiyas con cero khoums",
        21.0 to "veintiún ouguiyas con cero khoums",
        81.25 to "ochenta y un ouguiyas con veinticinco khoums",
        350.9 to "trescientos cincuenta ouguiyas con noventa khoums",
        100.0 to "cien ouguiyas con cero khoums",
        4150.83 to "cuatro mil ciento cincuenta ouguiyas con ochenta y tres khoums",
    )
    private val TEST_CASES_TO_CURRENCY_MUR = listOf<Pair<Any, String>>(
        1.0 to "una rupia con cero céntimos",
        2.0 to "dos rupias con cero céntimos",
        8.0 to "ocho rupias con cero céntimos",
        12.0 to "doce rupias con cero céntimos",
        21.0 to "veintiuna rupias con cero céntimos",
        81.25 to "ochenta y una rupias con veinticinco céntimos",
        350.9 to "trescientas cincuenta rupias con noventa céntimos",
        100.0 to "cien rupias con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta rupias con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_MVR = listOf<Pair<Any, String>>(
        1.0 to "un rufiyaa con cero laari",
        2.0 to "dos rufiyaas con cero laari",
        8.0 to "ocho rufiyaas con cero laari",
        12.0 to "doce rufiyaas con cero laari",
        21.0 to "veintiún rufiyaas con cero laari",
        81.25 to "ochenta y un rufiyaas con veinticinco laari",
        350.9 to "trescientos cincuenta rufiyaas con noventa laari",
        100.0 to "cien rufiyaas con cero laari",
        4150.83 to "cuatro mil ciento cincuenta rufiyaas con ochenta y tres laari",
    )
    private val TEST_CASES_TO_CURRENCY_MWK = listOf<Pair<Any, String>>(
        1.0 to "un kuacha con cero tambalas",
        2.0 to "dos kuachas con cero tambalas",
        8.0 to "ocho kuachas con cero tambalas",
        12.0 to "doce kuachas con cero tambalas",
        21.0 to "veintiún kuachas con cero tambalas",
        81.25 to "ochenta y un kuachas con veinticinco tambalas",
        350.9 to "trescientos cincuenta kuachas con noventa tambalas",
        100.0 to "cien kuachas con cero tambalas",
        4150.83 to "cuatro mil ciento cincuenta kuachas con ochenta y tres tambalas",
    )
    private val TEST_CASES_TO_CURRENCY_MXN = listOf<Pair<Any, String>>(
        1.0 to "un peso con cero centavos",
        2.0 to "dos pesos con cero centavos",
        8.0 to "ocho pesos con cero centavos",
        12.0 to "doce pesos con cero centavos",
        21.0 to "veintiún pesos con cero centavos",
        81.25 to "ochenta y un pesos con veinticinco centavos",
        350.9 to "trescientos cincuenta pesos con noventa centavos",
        100.0 to "cien pesos con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta pesos con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_MYR = listOf<Pair<Any, String>>(
        1.0 to "un ringgit con cero céntimos",
        2.0 to "dos ringgit con cero céntimos",
        8.0 to "ocho ringgit con cero céntimos",
        12.0 to "doce ringgit con cero céntimos",
        21.0 to "veintiún ringgit con cero céntimos",
        81.25 to "ochenta y un ringgit con veinticinco céntimos",
        350.9 to "trescientos cincuenta ringgit con noventa céntimos",
        100.0 to "cien ringgit con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta ringgit con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_MZN = listOf<Pair<Any, String>>(
        1.0 to "un metical con cero centavos",
        2.0 to "dos metical con cero centavos",
        8.0 to "ocho metical con cero centavos",
        12.0 to "doce metical con cero centavos",
        21.0 to "veintiún metical con cero centavos",
        81.25 to "ochenta y un metical con veinticinco centavos",
        350.9 to "trescientos cincuenta metical con noventa centavos",
        100.0 to "cien metical con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta metical con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_NGN = listOf<Pair<Any, String>>(
        1.0 to "un naira con cero kobo",
        2.0 to "dos nairas con cero kobo",
        8.0 to "ocho nairas con cero kobo",
        12.0 to "doce nairas con cero kobo",
        21.0 to "veintiún nairas con cero kobo",
        81.25 to "ochenta y un nairas con veinticinco kobo",
        350.9 to "trescientos cincuenta nairas con noventa kobo",
        100.0 to "cien nairas con cero kobo",
        4150.83 to "cuatro mil ciento cincuenta nairas con ochenta y tres kobo",
    )
    private val TEST_CASES_TO_CURRENCY_NIO = listOf<Pair<Any, String>>(
        1.0 to "un córdoba con cero centavos",
        2.0 to "dos córdobas con cero centavos",
        8.0 to "ocho córdobas con cero centavos",
        12.0 to "doce córdobas con cero centavos",
        21.0 to "veintiún córdobas con cero centavos",
        81.25 to "ochenta y un córdobas con veinticinco centavos",
        350.9 to "trescientos cincuenta córdobas con noventa centavos",
        100.0 to "cien córdobas con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta córdobas con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_NOK = listOf<Pair<Any, String>>(
        1.0 to "una corona con cero øre",
        2.0 to "dos coronas con cero øre",
        8.0 to "ocho coronas con cero øre",
        12.0 to "doce coronas con cero øre",
        21.0 to "veintiuna coronas con cero øre",
        81.25 to "ochenta y una coronas con veinticinco øre",
        350.9 to "trescientas cincuenta coronas con noventa øre",
        100.0 to "cien coronas con cero øre",
        4150.83 to "cuatro mil ciento cincuenta coronas con ochenta y tres øre",
    )
    private val TEST_CASES_TO_CURRENCY_NPR = listOf<Pair<Any, String>>(
        1.0 to "una rupia con cero paisas",
        2.0 to "dos rupias con cero paisas",
        8.0 to "ocho rupias con cero paisas",
        12.0 to "doce rupias con cero paisas",
        21.0 to "veintiuna rupias con cero paisas",
        81.25 to "ochenta y una rupias con veinticinco paisas",
        350.9 to "trescientas cincuenta rupias con noventa paisas",
        100.0 to "cien rupias con cero paisas",
        4150.83 to "cuatro mil ciento cincuenta rupias con ochenta y tres paisas",
    )
    private val TEST_CASES_TO_CURRENCY_OMR = listOf<Pair<Any, String>>(
        1.0 to "un rial con cero baisa",
        2.0 to "dos riales con cero baisa",
        8.0 to "ocho riales con cero baisa",
        12.0 to "doce riales con cero baisa",
        21.0 to "veintiún riales con cero baisa",
        81.25 to "ochenta y un riales con veinticinco baisa",
        350.9 to "trescientos cincuenta riales con noventa baisa",
        100.0 to "cien riales con cero baisa",
        4150.83 to "cuatro mil ciento cincuenta riales con ochenta y tres baisa",
    )
    private val TEST_CASES_TO_CURRENCY_PAB = listOf<Pair<Any, String>>(
        1.0 to "un balboa con cero centésimos",
        2.0 to "dos balboas con cero centésimos",
        8.0 to "ocho balboas con cero centésimos",
        12.0 to "doce balboas con cero centésimos",
        21.0 to "veintiún balboas con cero centésimos",
        81.25 to "ochenta y un balboas con veinticinco centésimos",
        350.9 to "trescientos cincuenta balboas con noventa centésimos",
        100.0 to "cien balboas con cero centésimos",
        4150.83 to "cuatro mil ciento cincuenta balboas con ochenta y tres centésimos",
    )
    private val TEST_CASES_TO_CURRENCY_PEN = listOf<Pair<Any, String>>(
        1.0 to "un sol con cero céntimos",
        2.0 to "dos soles con cero céntimos",
        8.0 to "ocho soles con cero céntimos",
        12.0 to "doce soles con cero céntimos",
        21.0 to "veintiún soles con cero céntimos",
        81.25 to "ochenta y un soles con veinticinco céntimos",
        350.9 to "trescientos cincuenta soles con noventa céntimos",
        100.0 to "cien soles con cero céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_PGK = listOf<Pair<Any, String>>(
        1.0 to "un kina con cero toea",
        2.0 to "dos kinas con cero toea",
        8.0 to "ocho kinas con cero toea",
        12.0 to "doce kinas con cero toea",
        21.0 to "veintiún kinas con cero toea",
        81.25 to "ochenta y un kinas con veinticinco toea",
        350.9 to "trescientos cincuenta kinas con noventa toea",
        100.0 to "cien kinas con cero toea",
        4150.83 to "cuatro mil ciento cincuenta kinas con ochenta y tres toea",
    )
    private val TEST_CASES_TO_CURRENCY_PKR = listOf<Pair<Any, String>>(
        1.0 to "una rupia con cero paisas",
        2.0 to "dos rupias con cero paisas",
        8.0 to "ocho rupias con cero paisas",
        12.0 to "doce rupias con cero paisas",
        21.0 to "veintiuna rupias con cero paisas",
        81.25 to "ochenta y una rupias con veinticinco paisas",
        350.9 to "trescientas cincuenta rupias con noventa paisas",
        100.0 to "cien rupias con cero paisas",
        4150.83 to "cuatro mil ciento cincuenta rupias con ochenta y tres paisas",
    )
    private val TEST_CASES_TO_CURRENCY_PLN = listOf<Pair<Any, String>>(
        1.0 to "un zloty con cero groszy",
        2.0 to "dos zlotys con cero groszy",
        8.0 to "ocho zlotys con cero groszy",
        12.0 to "doce zlotys con cero groszy",
        21.0 to "veintiún zlotys con cero groszy",
        81.25 to "ochenta y un zlotys con veinticinco groszy",
        350.9 to "trescientos cincuenta zlotys con noventa groszy",
        100.0 to "cien zlotys con cero groszy",
        4150.83 to "cuatro mil ciento cincuenta zlotys con ochenta y tres groszy",
    )
    private val TEST_CASES_TO_CURRENCY_PLZ = listOf<Pair<Any, String>>(
        1.0 to "un zloty con cero groszy",
        2.0 to "dos zlotys con cero groszy",
        8.0 to "ocho zlotys con cero groszy",
        12.0 to "doce zlotys con cero groszy",
        21.0 to "veintiún zlotys con cero groszy",
        81.25 to "ochenta y un zlotys con veinticinco groszy",
        350.9 to "trescientos cincuenta zlotys con noventa groszy",
        100.0 to "cien zlotys con cero groszy",
        4150.83 to "cuatro mil ciento cincuenta zlotys con ochenta y tres groszy",
    )
    private val TEST_CASES_TO_CURRENCY_PYG = listOf<Pair<Any, String>>(
        1.0 to "un guaraní con cero céntimos",
        2.0 to "dos guaranís con cero céntimos",
        8.0 to "ocho guaranís con cero céntimos",
        12.0 to "doce guaranís con cero céntimos",
        21.0 to "veintiún guaranís con cero céntimos",
        81.25 to "ochenta y un guaranís con veinticinco céntimos",
        350.9 to "trescientos cincuenta guaranís con noventa céntimos",
        100.0 to "cien guaranís con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta guaranís con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_QAR = listOf<Pair<Any, String>>(
        1.0 to "un rial con cero dírhams",
        2.0 to "dos riales con cero dírhams",
        8.0 to "ocho riales con cero dírhams",
        12.0 to "doce riales con cero dírhams",
        21.0 to "veintiún riales con cero dírhams",
        81.25 to "ochenta y un riales con veinticinco dírhams",
        350.9 to "trescientos cincuenta riales con noventa dírhams",
        100.0 to "cien riales con cero dírhams",
        4150.83 to "cuatro mil ciento cincuenta riales con ochenta y tres dírhams",
    )
    private val TEST_CASES_TO_CURRENCY_RON = listOf<Pair<Any, String>>(
        1.0 to "un leu con cero bani",
        2.0 to "dos leus con cero bani",
        8.0 to "ocho leus con cero bani",
        12.0 to "doce leus con cero bani",
        21.0 to "veintiún leus con cero bani",
        81.25 to "ochenta y un leus con veinticinco bani",
        350.9 to "trescientos cincuenta leus con noventa bani",
        100.0 to "cien leus con cero bani",
        4150.83 to "cuatro mil ciento cincuenta leus con ochenta y tres bani",
    )
    private val TEST_CASES_TO_CURRENCY_RSD = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero para",
        2.0 to "dos dinares con cero para",
        8.0 to "ocho dinares con cero para",
        12.0 to "doce dinares con cero para",
        21.0 to "veintiún dinares con cero para",
        81.25 to "ochenta y un dinares con veinticinco para",
        350.9 to "trescientos cincuenta dinares con noventa para",
        100.0 to "cien dinares con cero para",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres para",
    )
    private val TEST_CASES_TO_CURRENCY_RUB = listOf<Pair<Any, String>>(
        1.0 to "un rublo con cero kopeykas",
        2.0 to "dos rublos con cero kopeykas",
        8.0 to "ocho rublos con cero kopeykas",
        12.0 to "doce rublos con cero kopeykas",
        21.0 to "veintiún rublos con cero kopeykas",
        81.25 to "ochenta y un rublos con veinticinco kopeykas",
        350.9 to "trescientos cincuenta rublos con noventa kopeykas",
        100.0 to "cien rublos con cero kopeykas",
        4150.83 to "cuatro mil ciento cincuenta rublos con ochenta y tres kopeykas",
    )
    private val TEST_CASES_TO_CURRENCY_RUR = listOf<Pair<Any, String>>(
        1.0 to "un rublo con cero kopeks",
        2.0 to "dos rublos con cero kopeks",
        8.0 to "ocho rublos con cero kopeks",
        12.0 to "doce rublos con cero kopeks",
        21.0 to "veintiún rublos con cero kopeks",
        81.25 to "ochenta y un rublos con veinticinco kopeks",
        350.9 to "trescientos cincuenta rublos con noventa kopeks",
        100.0 to "cien rublos con cero kopeks",
        4150.83 to "cuatro mil ciento cincuenta rublos con ochenta y tres kopeks",
    )
    private val TEST_CASES_TO_CURRENCY_SAR = listOf<Pair<Any, String>>(
        1.0 to "un riyal con cero halalas",
        2.0 to "dos riales con cero halalas",
        8.0 to "ocho riales con cero halalas",
        12.0 to "doce riales con cero halalas",
        21.0 to "veintiún riales con cero halalas",
        81.25 to "ochenta y un riales con veinticinco halalas",
        350.9 to "trescientos cincuenta riales con noventa halalas",
        100.0 to "cien riales con cero halalas",
        4150.83 to "cuatro mil ciento cincuenta riales con ochenta y tres halalas",
    )
    private val TEST_CASES_TO_CURRENCY_SCR = listOf<Pair<Any, String>>(
        1.0 to "una rupia con cero céntimos",
        2.0 to "dos rupias con cero céntimos",
        8.0 to "ocho rupias con cero céntimos",
        12.0 to "doce rupias con cero céntimos",
        21.0 to "veintiuna rupias con cero céntimos",
        81.25 to "ochenta y una rupias con veinticinco céntimos",
        350.9 to "trescientas cincuenta rupias con noventa céntimos",
        100.0 to "cien rupias con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta rupias con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_SEK = listOf<Pair<Any, String>>(
        1.0 to "una corona con cero öre",
        2.0 to "dos coronas con cero öre",
        8.0 to "ocho coronas con cero öre",
        12.0 to "doce coronas con cero öre",
        21.0 to "veintiuna coronas con cero öre",
        81.25 to "ochenta y una coronas con veinticinco öre",
        350.9 to "trescientas cincuenta coronas con noventa öre",
        100.0 to "cien coronas con cero öre",
        4150.83 to "cuatro mil ciento cincuenta coronas con ochenta y tres öre",
    )
    private val TEST_CASES_TO_CURRENCY_SHP = listOf<Pair<Any, String>>(
        1.0 to "una libra con cero peniques",
        2.0 to "dos libras con cero peniques",
        8.0 to "ocho libras con cero peniques",
        12.0 to "doce libras con cero peniques",
        21.0 to "veintiuna libras con cero peniques",
        81.25 to "ochenta y una libras con veinticinco peniques",
        350.9 to "trescientas cincuenta libras con noventa peniques",
        100.0 to "cien libras con cero peniques",
        4150.83 to "cuatro mil ciento cincuenta libras con ochenta y tres peniques",
    )
    private val TEST_CASES_TO_CURRENCY_SKK = listOf<Pair<Any, String>>(
        1.0 to "una corona con cero haliers",
        2.0 to "dos coronas con cero haliers",
        8.0 to "ocho coronas con cero haliers",
        12.0 to "doce coronas con cero haliers",
        21.0 to "veintiuna coronas con cero haliers",
        81.25 to "ochenta y una coronas con veinticinco haliers",
        350.9 to "trescientas cincuenta coronas con noventa haliers",
        100.0 to "cien coronas con cero haliers",
        4150.83 to "cuatro mil ciento cincuenta coronas con ochenta y tres haliers",
    )
    private val TEST_CASES_TO_CURRENCY_SLL = listOf<Pair<Any, String>>(
        1.0 to "una leona con cero céntimos",
        2.0 to "dos leonas con cero céntimos",
        8.0 to "ocho leonas con cero céntimos",
        12.0 to "doce leonas con cero céntimos",
        21.0 to "veintiuna leonas con cero céntimos",
        81.25 to "ochenta y una leonas con veinticinco céntimos",
        350.9 to "trescientas cincuenta leonas con noventa céntimos",
        100.0 to "cien leonas con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta leonas con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_STD = listOf<Pair<Any, String>>(
        1.0 to "un dobra con cero céntimos",
        2.0 to "dos dobras con cero céntimos",
        8.0 to "ocho dobras con cero céntimos",
        12.0 to "doce dobras con cero céntimos",
        21.0 to "veintiún dobras con cero céntimos",
        81.25 to "ochenta y un dobras con veinticinco céntimos",
        350.9 to "trescientos cincuenta dobras con noventa céntimos",
        100.0 to "cien dobras con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta dobras con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_SVC = listOf<Pair<Any, String>>(
        1.0 to "un colón con cero centavos",
        2.0 to "dos colones con cero centavos",
        8.0 to "ocho colones con cero centavos",
        12.0 to "doce colones con cero centavos",
        21.0 to "veintiún colones con cero centavos",
        81.25 to "ochenta y un colones con veinticinco centavos",
        350.9 to "trescientos cincuenta colones con noventa centavos",
        100.0 to "cien colones con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta colones con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_SZL = listOf<Pair<Any, String>>(
        1.0 to "un lilangeni con cero céntimos",
        2.0 to "dos emalangeni con cero céntimos",
        8.0 to "ocho emalangeni con cero céntimos",
        12.0 to "doce emalangeni con cero céntimos",
        21.0 to "veintiún emalangeni con cero céntimos",
        81.25 to "ochenta y un emalangeni con veinticinco céntimos",
        350.9 to "trescientos cincuenta emalangeni con noventa céntimos",
        100.0 to "cien emalangeni con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta emalangeni con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_THB = listOf<Pair<Any, String>>(
        1.0 to "un baht con cero satang",
        2.0 to "dos bahts con cero satang",
        8.0 to "ocho bahts con cero satang",
        12.0 to "doce bahts con cero satang",
        21.0 to "veintiún bahts con cero satang",
        81.25 to "ochenta y un bahts con veinticinco satang",
        350.9 to "trescientos cincuenta bahts con noventa satang",
        100.0 to "cien bahts con cero satang",
        4150.83 to "cuatro mil ciento cincuenta bahts con ochenta y tres satang",
    )
    private val TEST_CASES_TO_CURRENCY_TJS = listOf<Pair<Any, String>>(
        1.0 to "un somoni con cero dirames",
        2.0 to "dos somonis con cero dirames",
        8.0 to "ocho somonis con cero dirames",
        12.0 to "doce somonis con cero dirames",
        21.0 to "veintiún somonis con cero dirames",
        81.25 to "ochenta y un somonis con veinticinco dirames",
        350.9 to "trescientos cincuenta somonis con noventa dirames",
        100.0 to "cien somonis con cero dirames",
        4150.83 to "cuatro mil ciento cincuenta somonis con ochenta y tres dirames",
    )
    private val TEST_CASES_TO_CURRENCY_TMT = listOf<Pair<Any, String>>(
        1.0 to "un manat con cero tenge",
        2.0 to "dos manat con cero tenge",
        8.0 to "ocho manat con cero tenge",
        12.0 to "doce manat con cero tenge",
        21.0 to "veintiún manat con cero tenge",
        81.25 to "ochenta y un manat con veinticinco tenge",
        350.9 to "trescientos cincuenta manat con noventa tenge",
        100.0 to "cien manat con cero tenge",
        4150.83 to "cuatro mil ciento cincuenta manat con ochenta y tres tenge",
    )
    private val TEST_CASES_TO_CURRENCY_TND = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero milésimos",
        2.0 to "dos dinares con cero milésimos",
        8.0 to "ocho dinares con cero milésimos",
        12.0 to "doce dinares con cero milésimos",
        21.0 to "veintiún dinares con cero milésimos",
        81.25 to "ochenta y un dinares con veinticinco milésimos",
        350.9 to "trescientos cincuenta dinares con noventa milésimos",
        100.0 to "cien dinares con cero milésimos",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres milésimos",
    )
    private val TEST_CASES_TO_CURRENCY_TOP = listOf<Pair<Any, String>>(
        1.0 to "un paanga con cero céntimos",
        2.0 to "dos paangas con cero céntimos",
        8.0 to "ocho paangas con cero céntimos",
        12.0 to "doce paangas con cero céntimos",
        21.0 to "veintiún paangas con cero céntimos",
        81.25 to "ochenta y un paangas con veinticinco céntimos",
        350.9 to "trescientos cincuenta paangas con noventa céntimos",
        100.0 to "cien paangas con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta paangas con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_TRY = listOf<Pair<Any, String>>(
        1.0 to "una lira con cero kuruş",
        2.0 to "dos liras con cero kuruş",
        8.0 to "ocho liras con cero kuruş",
        12.0 to "doce liras con cero kuruş",
        21.0 to "veintiuna liras con cero kuruş",
        81.25 to "ochenta y una liras con veinticinco kuruş",
        350.9 to "trescientas cincuenta liras con noventa kuruş",
        100.0 to "cien liras con cero kuruş",
        4150.83 to "cuatro mil ciento cincuenta liras con ochenta y tres kuruş",
    )
    private val TEST_CASES_TO_CURRENCY_TWD = listOf<Pair<Any, String>>(
        1.0 to "un nuevo dólar con cero céntimos",
        2.0 to "dos nuevos dólares con cero céntimos",
        8.0 to "ocho nuevos dólares con cero céntimos",
        12.0 to "doce nuevos dólares con cero céntimos",
        21.0 to "veintiún nuevos dólares con cero céntimos",
        81.25 to "ochenta y un nuevos dólares con veinticinco céntimos",
        350.9 to "trescientos cincuenta nuevos dólares con noventa céntimos",
        100.0 to "cien nuevos dólares con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta nuevos dólares con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_TZS = listOf<Pair<Any, String>>(
        1.0 to "un chelín con cero céntimos",
        2.0 to "dos chelines con cero céntimos",
        8.0 to "ocho chelines con cero céntimos",
        12.0 to "doce chelines con cero céntimos",
        21.0 to "veintiún chelines con cero céntimos",
        81.25 to "ochenta y un chelines con veinticinco céntimos",
        350.9 to "trescientos cincuenta chelines con noventa céntimos",
        100.0 to "cien chelines con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta chelines con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_UAG = listOf<Pair<Any, String>>(
        1.0 to "un hryvnia con cero kopiykas",
        2.0 to "dos hryvnias con cero kopiykas",
        8.0 to "ocho hryvnias con cero kopiykas",
        12.0 to "doce hryvnias con cero kopiykas",
        21.0 to "veintiún hryvnias con cero kopiykas",
        81.25 to "ochenta y un hryvnias con veinticinco kopiykas",
        350.9 to "trescientos cincuenta hryvnias con noventa kopiykas",
        100.0 to "cien hryvnias con cero kopiykas",
        4150.83 to "cuatro mil ciento cincuenta hryvnias con ochenta y tres kopiykas",
    )
    private val TEST_CASES_TO_CURRENCY_UAH = listOf<Pair<Any, String>>(
        1.0 to "un hryvnia con cero kopiykas",
        2.0 to "dos hryvnias con cero kopiykas",
        8.0 to "ocho hryvnias con cero kopiykas",
        12.0 to "doce hryvnias con cero kopiykas",
        21.0 to "veintiún hryvnias con cero kopiykas",
        81.25 to "ochenta y un hryvnias con veinticinco kopiykas",
        350.9 to "trescientos cincuenta hryvnias con noventa kopiykas",
        100.0 to "cien hryvnias con cero kopiykas",
        4150.83 to "cuatro mil ciento cincuenta hryvnias con ochenta y tres kopiykas",
    )
    private val TEST_CASES_TO_CURRENCY_UGX = listOf<Pair<Any, String>>(
        1.0 to "un chelín con cero céntimos",
        2.0 to "dos chelines con cero céntimos",
        8.0 to "ocho chelines con cero céntimos",
        12.0 to "doce chelines con cero céntimos",
        21.0 to "veintiún chelines con cero céntimos",
        81.25 to "ochenta y un chelines con veinticinco céntimos",
        350.9 to "trescientos cincuenta chelines con noventa céntimos",
        100.0 to "cien chelines con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta chelines con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_USD = listOf<Pair<Any, String>>(
        1.0 to "un dólar con cero centavos",
        2.0 to "dos dólares con cero centavos",
        8.0 to "ocho dólares con cero centavos",
        12.0 to "doce dólares con cero centavos",
        21.0 to "veintiún dólares con cero centavos",
        81.25 to "ochenta y un dólares con veinticinco centavos",
        350.9 to "trescientos cincuenta dólares con noventa centavos",
        100.0 to "cien dólares con cero centavos",
    )
    private val TEST_CASES_TO_CURRENCY_UYU = listOf<Pair<Any, String>>(
        1.0 to "un peso con cero centésimos",
        2.0 to "dos pesos con cero centésimos",
        8.0 to "ocho pesos con cero centésimos",
        12.0 to "doce pesos con cero centésimos",
        21.0 to "veintiún pesos con cero centésimos",
        81.25 to "ochenta y un pesos con veinticinco centésimos",
        350.9 to "trescientos cincuenta pesos con noventa centésimos",
        100.0 to "cien pesos con cero centésimos",
        4150.83 to "cuatro mil ciento cincuenta pesos con ochenta y tres centésimos",
    )
    private val TEST_CASES_TO_CURRENCY_UZS = listOf<Pair<Any, String>>(
        1.0 to "un sum con cero tiyin",
        2.0 to "dos sum con cero tiyin",
        8.0 to "ocho sum con cero tiyin",
        12.0 to "doce sum con cero tiyin",
        21.0 to "veintiún sum con cero tiyin",
        81.25 to "ochenta y un sum con veinticinco tiyin",
        350.9 to "trescientos cincuenta sum con noventa tiyin",
        100.0 to "cien sum con cero tiyin",
        4150.83 to "cuatro mil ciento cincuenta sum con ochenta y tres tiyin",
    )
    private val TEST_CASES_TO_CURRENCY_VEF = listOf<Pair<Any, String>>(
        1.0 to "un bolívar fuerte con cero céntimos",
        2.0 to "dos bolívares fuertes con cero céntimos",
        8.0 to "ocho bolívares fuertes con cero céntimos",
        12.0 to "doce bolívares fuertes con cero céntimos",
        21.0 to "veintiún bolívares fuertes con cero céntimos",
        81.25 to "ochenta y un bolívares fuertes con veinticinco céntimos",
        350.9 to "trescientos cincuenta bolívares fuertes con noventa céntimos",
        100.0 to "cien bolívares fuertes con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta bolívares fuertes con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_VES = listOf<Pair<Any, String>>(
        1.0 to "un bolívar con cero céntimos",
        2.0 to "dos bolívares con cero céntimos",
        8.0 to "ocho bolívares con cero céntimos",
        12.0 to "doce bolívares con cero céntimos",
        21.0 to "veintiún bolívares con cero céntimos",
        81.25 to "ochenta y un bolívares con veinticinco céntimos",
        350.9 to "trescientos cincuenta bolívares con noventa céntimos",
        100.0 to "cien bolívares con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta bolívares con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_VND = listOf<Pair<Any, String>>(
        1.0 to "un dong con cero xu",
        2.0 to "dos dongs con cero xu",
        8.0 to "ocho dongs con cero xu",
        12.0 to "doce dongs con cero xu",
        21.0 to "veintiún dongs con cero xu",
        81.25 to "ochenta y un dongs con veinticinco xu",
        350.9 to "trescientos cincuenta dongs con noventa xu",
        100.0 to "cien dongs con cero xu",
        4150.83 to "cuatro mil ciento cincuenta dongs con ochenta y tres xu",
    )
    private val TEST_CASES_TO_CURRENCY_VUV = listOf<Pair<Any, String>>(
        1.0 to "un vatu con cero nenhum",
        2.0 to "dos vatu con cero nenhum",
        8.0 to "ocho vatu con cero nenhum",
        12.0 to "doce vatu con cero nenhum",
        21.0 to "veintiún vatu con cero nenhum",
        81.25 to "ochenta y un vatu con veinticinco nenhum",
        350.9 to "trescientos cincuenta vatu con noventa nenhum",
        100.0 to "cien vatu con cero nenhum",
        4150.83 to "cuatro mil ciento cincuenta vatu con ochenta y tres nenhum",
    )
    private val TEST_CASES_TO_CURRENCY_WST = listOf<Pair<Any, String>>(
        1.0 to "un tala con cero centavos",
        2.0 to "dos tala con cero centavos",
        8.0 to "ocho tala con cero centavos",
        12.0 to "doce tala con cero centavos",
        21.0 to "veintiún tala con cero centavos",
        81.25 to "ochenta y un tala con veinticinco centavos",
        350.9 to "trescientos cincuenta tala con noventa centavos",
        100.0 to "cien tala con cero centavos",
        4150.83 to "cuatro mil ciento cincuenta tala con ochenta y tres centavos",
    )
    private val TEST_CASES_TO_CURRENCY_XAF = listOf<Pair<Any, String>>(
        1.0 to "un franco CFA con cero céntimos",
        2.0 to "dos francos CFA con cero céntimos",
        8.0 to "ocho francos CFA con cero céntimos",
        12.0 to "doce francos CFA con cero céntimos",
        21.0 to "veintiún francos CFA con cero céntimos",
        81.25 to "ochenta y un francos CFA con veinticinco céntimos",
        350.9 to "trescientos cincuenta francos CFA con noventa céntimos",
        100.0 to "cien francos CFA con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta francos CFA con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_XPF = listOf<Pair<Any, String>>(
        1.0 to "un franco CFP con cero céntimos",
        2.0 to "dos francos CFP con cero céntimos",
        8.0 to "ocho francos CFP con cero céntimos",
        12.0 to "doce francos CFP con cero céntimos",
        21.0 to "veintiún francos CFP con cero céntimos",
        81.25 to "ochenta y un francos CFP con veinticinco céntimos",
        350.9 to "trescientos cincuenta francos CFP con noventa céntimos",
        100.0 to "cien francos CFP con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta francos CFP con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_YER = listOf<Pair<Any, String>>(
        1.0 to "un rial con cero fils",
        2.0 to "dos riales con cero fils",
        8.0 to "ocho riales con cero fils",
        12.0 to "doce riales con cero fils",
        21.0 to "veintiún riales con cero fils",
        81.25 to "ochenta y un riales con veinticinco fils",
        350.9 to "trescientos cincuenta riales con noventa fils",
        100.0 to "cien riales con cero fils",
        4150.83 to "cuatro mil ciento cincuenta riales con ochenta y tres fils",
    )
    private val TEST_CASES_TO_CURRENCY_YUM = listOf<Pair<Any, String>>(
        1.0 to "un dinar con cero para",
        2.0 to "dos dinares con cero para",
        8.0 to "ocho dinares con cero para",
        12.0 to "doce dinares con cero para",
        21.0 to "veintiún dinares con cero para",
        81.25 to "ochenta y un dinares con veinticinco para",
        350.9 to "trescientos cincuenta dinares con noventa para",
        100.0 to "cien dinares con cero para",
        4150.83 to "cuatro mil ciento cincuenta dinares con ochenta y tres para",
    )
    private val TEST_CASES_TO_CURRENCY_ZAR = listOf<Pair<Any, String>>(
        1.0 to "un rand con cero céntimos",
        2.0 to "dos rands con cero céntimos",
        8.0 to "ocho rands con cero céntimos",
        12.0 to "doce rands con cero céntimos",
        21.0 to "veintiún rands con cero céntimos",
        81.25 to "ochenta y un rands con veinticinco céntimos",
        350.9 to "trescientos cincuenta rands con noventa céntimos",
        100.0 to "cien rands con cero céntimos",
        4150.83 to "cuatro mil ciento cincuenta rands con ochenta y tres céntimos",
    )
    private val TEST_CASES_TO_CURRENCY_ZMW = listOf<Pair<Any, String>>(
        1.0 to "un kwacha con cero ngwee",
        2.0 to "dos kwachas con cero ngwee",
        8.0 to "ocho kwachas con cero ngwee",
        12.0 to "doce kwachas con cero ngwee",
        21.0 to "veintiún kwachas con cero ngwee",
        81.25 to "ochenta y un kwachas con veinticinco ngwee",
        350.9 to "trescientos cincuenta kwachas con noventa ngwee",
        100.0 to "cien kwachas con cero ngwee",
        4150.83 to "cuatro mil ciento cincuenta kwachas con ochenta y tres ngwee",
    )
    private val TEST_CASES_TO_CURRENCY_ZRZ = listOf<Pair<Any, String>>(
        1.0 to "un zaire con cero makuta",
        2.0 to "dos zaires con cero makuta",
        8.0 to "ocho zaires con cero makuta",
        12.0 to "doce zaires con cero makuta",
        21.0 to "veintiún zaires con cero makuta",
        81.25 to "ochenta y un zaires con veinticinco makuta",
        350.9 to "trescientos cincuenta zaires con noventa makuta",
        100.0 to "cien zaires con cero makuta",
        4150.83 to "cuatro mil ciento cincuenta zaires con ochenta y tres makuta",
    )

    @Test
    fun number() {
        for ((v, e) in CARDINAL) assertEquals(e, esNum(v))
    }
    @Test
    fun ordinal() {
        for ((v, e) in ORDINAL) assertEquals(e, esNum(v, to = "ordinal"))
    }
    @Test
    fun ordinalFem() {
        for ((v, e) in ORDINAL_FEM) assertEquals(
            e,
            esNum(v, to = "ordinal", options = mapOf("gender" to "f")),
        )
    }
    @Test
    fun ordinalNum() {
        for ((v, e) in ORDINAL_NUM) assertEquals(e, esNum(v, to = "ordinal_num"))
    }
    @Test
    fun currencyDefault() {
        for ((v, e) in TEST_CASES_TO_CURRENCY) assertEquals(e, esNum(v, to = "currency"))
    }
    @Test
    fun currencyPerCode() {
        val per = mapOf(
            "AED" to TEST_CASES_TO_CURRENCY_AED,
            "AFN" to TEST_CASES_TO_CURRENCY_AFN,
            "ALL" to TEST_CASES_TO_CURRENCY_ALL,
            "AMD" to TEST_CASES_TO_CURRENCY_AMD,
            "ANG" to TEST_CASES_TO_CURRENCY_ANG,
            "AOA" to TEST_CASES_TO_CURRENCY_AOA,
            "AWG" to TEST_CASES_TO_CURRENCY_AWG,
            "AZN" to TEST_CASES_TO_CURRENCY_AZN,
            "BDT" to TEST_CASES_TO_CURRENCY_BDT,
            "BGN" to TEST_CASES_TO_CURRENCY_BGN,
            "BHD" to TEST_CASES_TO_CURRENCY_BHD,
            "BOB" to TEST_CASES_TO_CURRENCY_BOB,
            "BRL" to TEST_CASES_TO_CURRENCY_BRL,
            "BTN" to TEST_CASES_TO_CURRENCY_BTN,
            "BWP" to TEST_CASES_TO_CURRENCY_BWP,
            "BYN" to TEST_CASES_TO_CURRENCY_BYN,
            "BYR" to TEST_CASES_TO_CURRENCY_BYR,
            "BZD" to TEST_CASES_TO_CURRENCY_BZD,
            "CNY" to TEST_CASES_TO_CURRENCY_CNY,
            "CRC" to TEST_CASES_TO_CURRENCY_CRC,
            "CVE" to TEST_CASES_TO_CURRENCY_CVE,
            "CYP" to TEST_CASES_TO_CURRENCY_CYP,
            "CZK" to TEST_CASES_TO_CURRENCY_CZK,
            "DKK" to TEST_CASES_TO_CURRENCY_DKK,
            "DZD" to TEST_CASES_TO_CURRENCY_DZD,
            "ECS" to TEST_CASES_TO_CURRENCY_ECS,
            "EGP" to TEST_CASES_TO_CURRENCY_EGP,
            "ERN" to TEST_CASES_TO_CURRENCY_ERN,
            "ESP" to TEST_CASES_TO_CURRENCY_ESP,
            "ETB" to TEST_CASES_TO_CURRENCY_ETB,
            "FKP" to TEST_CASES_TO_CURRENCY_FKP,
            "FRF" to TEST_CASES_TO_CURRENCY_FRF,
            "GBP" to TEST_CASES_TO_CURRENCY_GBP,
            "GEL" to TEST_CASES_TO_CURRENCY_GEL,
            "GHS" to TEST_CASES_TO_CURRENCY_GHS,
            "GMD" to TEST_CASES_TO_CURRENCY_GMD,
            "GTQ" to TEST_CASES_TO_CURRENCY_GTQ,
            "HNL" to TEST_CASES_TO_CURRENCY_HNL,
            "HRK" to TEST_CASES_TO_CURRENCY_HRK,
            "HTG" to TEST_CASES_TO_CURRENCY_HTG,
            "HUF" to TEST_CASES_TO_CURRENCY_HUF,
            "IDR" to TEST_CASES_TO_CURRENCY_IDR,
            "ILS" to TEST_CASES_TO_CURRENCY_ILS,
            "INR" to TEST_CASES_TO_CURRENCY_INR,
            "IQD" to TEST_CASES_TO_CURRENCY_IQD,
            "IRR" to TEST_CASES_TO_CURRENCY_IRR,
            "ISK" to TEST_CASES_TO_CURRENCY_ISK,
            "ITL" to TEST_CASES_TO_CURRENCY_ITL,
            "JOD" to TEST_CASES_TO_CURRENCY_JOD,
            "JPY" to TEST_CASES_TO_CURRENCY_JPY,
            "KES" to TEST_CASES_TO_CURRENCY_KES,
            "KGS" to TEST_CASES_TO_CURRENCY_KGS,
            "KHR" to TEST_CASES_TO_CURRENCY_KHR,
            "KPW" to TEST_CASES_TO_CURRENCY_KPW,
            "KRW" to TEST_CASES_TO_CURRENCY_KRW,
            "KWD" to TEST_CASES_TO_CURRENCY_KWD,
            "KZT" to TEST_CASES_TO_CURRENCY_KZT,
            "LAK" to TEST_CASES_TO_CURRENCY_LAK,
            "LKR" to TEST_CASES_TO_CURRENCY_LKR,
            "LSL" to TEST_CASES_TO_CURRENCY_LSL,
            "LTL" to TEST_CASES_TO_CURRENCY_LTL,
            "LVL" to TEST_CASES_TO_CURRENCY_LVL,
            "LYD" to TEST_CASES_TO_CURRENCY_LYD,
            "MAD" to TEST_CASES_TO_CURRENCY_MAD,
            "MDL" to TEST_CASES_TO_CURRENCY_MDL,
            "MGA" to TEST_CASES_TO_CURRENCY_MGA,
            "MKD" to TEST_CASES_TO_CURRENCY_MKD,
            "MMK" to TEST_CASES_TO_CURRENCY_MMK,
            "MNT" to TEST_CASES_TO_CURRENCY_MNT,
            "MOP" to TEST_CASES_TO_CURRENCY_MOP,
            "MRO" to TEST_CASES_TO_CURRENCY_MRO,
            "MRU" to TEST_CASES_TO_CURRENCY_MRU,
            "MUR" to TEST_CASES_TO_CURRENCY_MUR,
            "MVR" to TEST_CASES_TO_CURRENCY_MVR,
            "MWK" to TEST_CASES_TO_CURRENCY_MWK,
            "MXN" to TEST_CASES_TO_CURRENCY_MXN,
            "MYR" to TEST_CASES_TO_CURRENCY_MYR,
            "MZN" to TEST_CASES_TO_CURRENCY_MZN,
            "NGN" to TEST_CASES_TO_CURRENCY_NGN,
            "NIO" to TEST_CASES_TO_CURRENCY_NIO,
            "NOK" to TEST_CASES_TO_CURRENCY_NOK,
            "NPR" to TEST_CASES_TO_CURRENCY_NPR,
            "OMR" to TEST_CASES_TO_CURRENCY_OMR,
            "PAB" to TEST_CASES_TO_CURRENCY_PAB,
            "PEN" to TEST_CASES_TO_CURRENCY_PEN,
            "PGK" to TEST_CASES_TO_CURRENCY_PGK,
            "PKR" to TEST_CASES_TO_CURRENCY_PKR,
            "PLN" to TEST_CASES_TO_CURRENCY_PLN,
            "PLZ" to TEST_CASES_TO_CURRENCY_PLZ,
            "PYG" to TEST_CASES_TO_CURRENCY_PYG,
            "QAR" to TEST_CASES_TO_CURRENCY_QAR,
            "RON" to TEST_CASES_TO_CURRENCY_RON,
            "RSD" to TEST_CASES_TO_CURRENCY_RSD,
            "RUB" to TEST_CASES_TO_CURRENCY_RUB,
            "RUR" to TEST_CASES_TO_CURRENCY_RUR,
            "SAR" to TEST_CASES_TO_CURRENCY_SAR,
            "SCR" to TEST_CASES_TO_CURRENCY_SCR,
            "SEK" to TEST_CASES_TO_CURRENCY_SEK,
            "SHP" to TEST_CASES_TO_CURRENCY_SHP,
            "SKK" to TEST_CASES_TO_CURRENCY_SKK,
            "SLL" to TEST_CASES_TO_CURRENCY_SLL,
            "STD" to TEST_CASES_TO_CURRENCY_STD,
            "SVC" to TEST_CASES_TO_CURRENCY_SVC,
            "SZL" to TEST_CASES_TO_CURRENCY_SZL,
            "THB" to TEST_CASES_TO_CURRENCY_THB,
            "TJS" to TEST_CASES_TO_CURRENCY_TJS,
            "TMT" to TEST_CASES_TO_CURRENCY_TMT,
            "TND" to TEST_CASES_TO_CURRENCY_TND,
            "TOP" to TEST_CASES_TO_CURRENCY_TOP,
            "TRY" to TEST_CASES_TO_CURRENCY_TRY,
            "TWD" to TEST_CASES_TO_CURRENCY_TWD,
            "TZS" to TEST_CASES_TO_CURRENCY_TZS,
            "UAG" to TEST_CASES_TO_CURRENCY_UAG,
            "UAH" to TEST_CASES_TO_CURRENCY_UAH,
            "UGX" to TEST_CASES_TO_CURRENCY_UGX,
            "USD" to TEST_CASES_TO_CURRENCY_USD,
            "UYU" to TEST_CASES_TO_CURRENCY_UYU,
            "UZS" to TEST_CASES_TO_CURRENCY_UZS,
            "VEF" to TEST_CASES_TO_CURRENCY_VEF,
            "VES" to TEST_CASES_TO_CURRENCY_VES,
            "VND" to TEST_CASES_TO_CURRENCY_VND,
            "VUV" to TEST_CASES_TO_CURRENCY_VUV,
            "WST" to TEST_CASES_TO_CURRENCY_WST,
            "XAF" to TEST_CASES_TO_CURRENCY_XAF,
            "XPF" to TEST_CASES_TO_CURRENCY_XPF,
            "YER" to TEST_CASES_TO_CURRENCY_YER,
            "YUM" to TEST_CASES_TO_CURRENCY_YUM,
            "ZAR" to TEST_CASES_TO_CURRENCY_ZAR,
            "ZMW" to TEST_CASES_TO_CURRENCY_ZMW,
            "ZRZ" to TEST_CASES_TO_CURRENCY_ZRZ,
        )
        for ((code, cases) in per) {
            for ((v, e) in cases) assertEquals(
                e,
                esNum(v, to = "currency", options = mapOf("currency" to code)),
            )
        }
        for ((v, e) in TEST_CASES_TO_CURRENCY_USD) {
            assertEquals(e, esNum(v, to = "currency", options = mapOf("currency" to "AUD")))
            assertEquals(e, esNum(v, to = "currency", options = mapOf("currency" to "CAD")))
        }
    }
}
